# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cam's Tech Blog
email: cammurphy195@gmail.com
description: A blog about technology.Built with Jekyll, hosted on Github Pages, and protected by Cloudflare. # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.cammurphy.com" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  cmurph56

# Build settings
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

# logo: "/assets/images/cam_profile_photo.jpg"


# MINIMAL MISTAKES CONFIGS
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
enable_copy_code_button: true
search: true

author_profile: true
author:
  name: "Cam Murphy"
  avatar: "/assets/images/cam_profile_photo.jpg"
  bio: "Software Developer / Cloud Engineer. I do a little bit of networking, security, and programming."
  location: "Chicago, Illinois"
  links:
    - label: "Mastodon"
      url: https://mastodon.social/@cmurphy56
      icon: "fab fa-fw fa-mastodon"
    - label: Github
      url: https://github.com/CMURPH56
      icon: "fab fa-fw fa-github"



defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: false
      show_date: true
      author_profile: true





plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache



lsi: false
safe: true
# source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
